<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Utils</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>libs/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule" />
    <Reference Include="System.Core">
      <HintPath>../../../../../../../nix/store/n57lnvd92db1qyka8m04ixv1qv4ayq7j-dotnet-sdk-8.0.424/share/dotnet/shared/Microsoft.NETCore.App/8.0.30/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="FMODUnity" />
    <Reference Include="UnityEngine.ParticleSystemModule" />
    <Reference Include="Unity.TextMeshPro" />
    <Reference Include="UnityEngine.AudioModule" />
    <Reference Include="UnityEngine.IMGUIModule" />
    <Reference Include="UnityEngine.UI">
      <HintPath>libs/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net" />
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>libs/UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule" />
    <Reference Include="UnityEngine.JSONSerializeModule" />
  </ItemGroup>
</Project>